[[section-solution-strategy]]

== Solution Strategy

=== Technology Decisions

The following technologies are used in the development of our application:

* *_React_*: JavaScript library required for building user interfaces for the web.

* *_JavaScript_*: Chosen language for application development.

* *_MongoDB_*: Default choice for non-relational database selected for the task.

=== Top-level Decomposition
==== IDE
We have chosen Visual Studio Code as our platform since we have experience with it and it is the platform we will work best with.

==== Diagram design tools
We will use PlantUML as the tool for creating diagrams since it is the recommended one for the course.

=== Key quality goals
-- In progress --

=== Organizational decisions
Here are the organization decisions made:
* *_Language_*: We will use English as the primary language for both documentation and code.
* *_GitHub issues_*: We will use GitHub issues as the main source for problem resolution, so that whenever something poses an obstacle, it will be documented in GitHub issues.
* *_GitHub projects_*: GitHub projects allow us to organize work based on issues in a Kanban-style, enabling us to see issues that are in progress, those that are not, and those that are completed.